import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './context/AuthProvider'
import { FilterProvider } from './context/FilterContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body className={inter.className}>
      <AuthProvider>
        <FilterProvider>
        {children}
        </FilterProvider>

      </AuthProvider>
      </body>
    </html>
  )
}
