import { TweetAnalysis } from './types';

export const tweetAnalysisData: TweetAnalysis[] = [
  {
    id: '1',
    content: 'ビジネス役立ち名言',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 2700,
    followerText: '2700フォロワー',
    replyTypes: ['響く', '勇気づけられた', '励みになる'],
    insights: 'わかりやすい',
    imageUrl: '/images/test/tweet-image-1.png',
    category: 'ビジネス'
  },
  {
    id: '2',
    content: '起業状況報告',
    hasImage: true,
    hasLink: true,
    hasReplies: false,
    followerCount: 44000,
    followerText: '4.4万フォロワー',
    replyTypes: [],
    insights: '実際はどうなの？ということで意見がまとめられている投稿。note自体は長文だが、いいね数を見ると読まれている',
    imageUrl: '/images/test/tweet-image-2.png',
    category: '起業'
  },
  {
    id: '3',
    content: '本紹介',
    hasImage: true,
    hasLink: true,
    hasReplies: true,
    followerCount: 27000,
    followerText: '2.7万フォロワー',
    replyTypes: ['買います！系'],
    insights: '本紹介でもインプレッションが多いが、これはフォロワーが多いから説',
    imageUrl: '/images/test/tweet-image-3.png',
    category: '本紹介'
  },
  {
    id: '4',
    content: 'ベーシックインカムの是非',
    hasImage: true,
    hasLink: true,
    hasReplies: true,
    followerCount: 2380000,
    followerText: '238万フォロワー',
    replyTypes: ['試験になるのか、どうなるのかという感想'],
    insights: '本紹介でもインプレッションが多いが、これはフォロワーが多いから説',
    imageUrl: '/images/test/tweet-image-4.png',
    category: '時事問題'
  },
  {
    id: '5',
    content: 'テクノロジー紹介',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 80000,
    followerText: '8万フォロワー',
    replyTypes: ['すごい', '役に立つ！'],
    insights: 'わかりやすいインパクトがある',
    imageUrl: '/images/test/tweet-image-5.png',
    category: 'テクノロジー'
  },
  {
    id: '6',
    content: 'テクノロジー紹介',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 80000,
    followerText: '8万フォロワー',
    replyTypes: ['すごい技術'],
    insights: 'ほんとかな？わかりやすい動画',
    imageUrl: '/images/test/tweet-image-6.png',
    category: 'テクノロジー'
  },
  {
    id: '7',
    content: 'AIハックお役立ち',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 7600,
    followerText: '7600フォロワー',
    replyTypes: ['賛否色々'],
    insights: '見やすい',
    imageUrl: '/images/test/tweet-image-7.png',
    category: 'AI'
  },
  {
    id: '8',
    content: 'AIハックお役立ち',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 7600,
    followerText: '7600フォロワー',
    replyTypes: ['賛否色々'],
    insights: '見やすい',
    imageUrl: '/images/test/tweet-image-8.png',
    category: 'AI'
  },
  {
    id: '9',
    content: 'AIハックお役立ち',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 7600,
    followerText: '7600フォロワー',
    replyTypes: ['賛否色々'],
    insights: '見やすい',
    imageUrl: '/images/test/tweet-image-9.png',
    category: 'AI'
  },
  {
    id: '10',
    content: '宇宙紹介',
    hasImage: true,
    hasLink: true,
    hasReplies: true,
    followerCount: 2300,
    followerText: '2300フォロワー',
    replyTypes: ['ワクワクする'],
    insights: 'ネットスラングっぽくてキャッチー',
    imageUrl: '/images/test/tweet-image-10.png',
    category: '宇宙'
  },
  {
    id: '11',
    content: '時事問題系の投稿',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 1300,
    followerText: '1300フォロワー',
    replyTypes: ['やるヤン的なコメント'],
    insights: '時事ネタ（ジャニーズ）に絡んでいる方が伸びやすいのか？',
    imageUrl: '/images/test/tweet-image-11.png',
    category: '時事問題'
  },
  {
    id: '12',
    content: 'ビジネス系',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 20000,
    followerText: '2万フォロワー',
    replyTypes: ['スタバすごい的なコメント'],
    insights: '引きがあって、画像をクリックしたくなる',
    imageUrl: '/images/test/tweet-image-12.png',
    category: 'ビジネス'
  },
  {
    id: '13',
    content: 'ビジネス系',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 5600,
    followerText: '5600フォロワー',
    replyTypes: ['共感コメント'],
    insights: 'プロフに誘引している、がフォローしたくなる感じでもない',
    imageUrl: '/images/test/tweet-image-13.png',
    category: 'ビジネス'
  },
  {
    id: '14',
    content: 'ライフプラン',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 36000,
    followerText: '3.6万フォロワー',
    replyTypes: ['役立ちます！的な'],
    insights: 'げんきになる系のツイート多い個人的には好感度高い',
    imageUrl: '/images/test/tweet-image-14.png',
    category: 'ライフプラン'
  },
  {
    id: '15',
    content: 'GPT図解',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 74000,
    followerText: '7.4万フォロワー',
    replyTypes: ['役立ちます！的な'],
    insights: '思わずクリックしました',
    imageUrl: '/images/test/tweet-image-15.png',
    category: 'AI'
  },
  {
    id: '16',
    content: 'スタバ戦略まとめ',
    hasImage: true,
    hasLink: false,
    hasReplies: true,
    followerCount: 31000,
    followerText: '3.1万フォロワー',
    replyTypes: ['なるほど！的な'],
    insights: '思わずクリックしました',
    imageUrl: '/images/test/tweet-image-16.png',
    category: 'ビジネス'
  }
];